// Feedback and Motivational Support Type Definitions

export type DifficultyRating = 'easy' | 'moderate' | 'difficult' | 'too-difficult';
export type PainLevel = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * Exercise session feedback collected from user
 */
export interface ExerciseFeedback {
  sessionId: string;
  userId: string;
  exerciseId: string;
  exerciseName: string;
  painExperienced: boolean;
  painLevel?: PainLevel; // 1-10 if pain = true
  difficultyRating: DifficultyRating;
  completed: boolean;
  notes?: string;
  timestamp: Date;
}

/**
 * Feedback response generated by decision tree
 */
export interface FeedbackResponse {
  message: string;
  type: 'motivation' | 'encouragement' | 'warning' | 'reminder' | 'adjustment';
  icon: string;
  suggestedAction?: string;
  adjustIntensity?: boolean;
}

/**
 * User's feedback history for personalization
 */
export interface FeedbackHistory {
  userId: string;
  feedbacks: ExerciseFeedback[];
  lastFeedbackDate: Date;
  averagePainLevel: number;
  averageDifficulty: number;
  completionRate: number;
}

/**
 * Reminder schedule settings
 */
export interface ReminderSchedule {
  userId: string;
  reminderTime: string; // "HH:MM" format (24-hour)
  frequency: 'daily' | 'every-other-day' | 'custom';
  customDays?: number[]; // 0-6 (Sunday-Saturday) for custom frequency
  enabled: boolean;
  timezone?: string;
}

/**
 * Notification message
 */
export interface NotificationMessage {
  userId: string;
  title: string;
  body: string;
  type: 'reminder' | 'encouragement' | 'achievement' | 'warning';
  scheduledTime?: Date;
  sent: boolean;
}
